export const initialNodes = [
    { id: 'source-code', type: 'universal', data: { title: 'Source Code', subtitle: 'Commit & Push', icon: '📝' }, position: { x: 50, y: 50 }, width: 280 },
    { id: 'ci-pipeline', type: 'universal', data: { title: 'CI Pipeline', subtitle: 'Build & Test', icon: '⚙️' }, position: { x: 50, y: 200 }, width: 280 },
    { id: 'docker-registry', type: 'universal', data: { title: 'Docker Registry', subtitle: 'Store Image', icon: '📦' }, position: { x: 300, y: 200 }, width: 280 },
    { id: 'gitops-repo', type: 'universal', data: { title: 'GitOps Repo', subtitle: 'Manifests', icon: '📜' }, position: { x: 550, y: 200 }, width: 280 },
    { id: 'argocd', type: 'universal', data: { title: 'Argo CD', subtitle: 'Sync Controller', icon: '🐙' }, position: { x: 550, y: 350 }, width: 280 },
    {
        id: 'k3d-cluster', type: 'group', data: { label: 'K3d Cluster' },
        position: { x: 250, y: 450 },
        style: {
            width: 520, height: 260,
            backgroundColor: 'rgba(30, 41, 59, 0.35)',
            border: '1px dashed rgba(148, 163, 184, 0.25)',
            borderRadius: '20px', color: 'rgba(248, 250, 252, 0.6)', fontWeight: 'bold', padding: '16px',
            backdropFilter: 'blur(8px)', WebkitBackdropFilter: 'blur(8px)',
            boxShadow: '0 4px 24px rgba(0, 0, 0, 0.3)',
        },
    },
    { id: 'deployment', type: 'universal', data: { title: 'Deployment', subtitle: 'Pods', icon: '🚀' }, position: { x: 40, y: 70 }, parentId: 'k3d-cluster', extent: 'parent', width: 180 },
    { id: 'service', type: 'universal', data: { title: 'Service', subtitle: 'LoadBalancer', icon: '🌐' }, position: { x: 280, y: 70 }, parentId: 'k3d-cluster', extent: 'parent', width: 180 },
    { id: 'user', type: 'universal', data: { title: 'End User', subtitle: '', icon: '👤' }, position: { x: 390, y: 750 }, width: 280 },
];

export const initialEdges = [
    { id: 'e1', source: 'source-code', target: 'ci-pipeline', type: 'viral', label: 'Push Code', style: { stroke: '#f97316' } },
    { id: 'e2', source: 'ci-pipeline', target: 'docker-registry', type: 'viral', label: 'Push Image', style: { stroke: '#8b5cf6' } },
    { id: 'e3', source: 'ci-pipeline', target: 'gitops-repo', type: 'viral', label: 'Update Tag', style: { stroke: '#8b5cf6' } },
    { id: 'e4', source: 'gitops-repo', target: 'argocd', type: 'viral', label: 'Watch', style: { stroke: '#f97316' } },
    { id: 'e5', source: 'argocd', target: 'deployment', type: 'viral', label: 'Sync', style: { stroke: '#06b6d4' } },
    { id: 'e6', source: 'docker-registry', target: 'deployment', type: 'viral', label: 'Pull Image', style: { stroke: '#a855f7' } },
    { id: 'e7', source: 'deployment', target: 'service', type: 'viral', style: { stroke: '#10b981' } },
    { id: 'e8', source: 'service', target: 'user', type: 'viral', label: 'Access', style: { stroke: '#ec4899' } },
];

export const groupDefaultStyle = {
    backgroundColor: 'rgba(30, 41, 59, 0.35)',
    border: '1px dashed rgba(148, 163, 184, 0.25)',
    borderRadius: '20px',
    color: 'rgba(248, 250, 252, 0.6)',
    fontWeight: 'bold',
    padding: '16px',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    boxShadow: '0 4px 24px rgba(0, 0, 0, 0.3)',
};

// Premium Node Theme System
export const NODE_THEMES = {
    vercel_glass: {
        name: 'Vercel Glass',
        emoji: '⚫',
        containerBase: {
            background: 'linear-gradient(145deg, rgba(0, 0, 0, 0.95) 0%, rgba(10, 10, 10, 0.95) 100%)',
            backdropFilter: 'blur(20px)',
            WebkitBackdropFilter: 'blur(20px)',
            border: '1px solid rgba(255, 255, 255, 0.08)',
            boxShadow: '0 24px 48px -12px rgba(0, 0, 0, 0.9), inset 0 1px 0 rgba(255, 255, 255, 0.1)',
            borderRadius: '20px',
            padding: '28px 36px',
            minWidth: '280px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
        },
        containerSelected: {
            boxShadow: '0 24px 48px -12px rgba(6, 182, 212, 0.5), 0 0 32px rgba(6, 182, 212, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.15)',
            border: '1px solid rgba(6, 182, 212, 0.6)',
            transform: 'scale(1.02)',
        },
        iconWrapper: {
            background: 'rgba(6, 182, 212, 0.08)',
            border: '1px solid rgba(6, 182, 212, 0.2)',
            boxShadow: '0 0 20px rgba(6, 182, 212, 0.15)',
            fontSize: '32px',
            padding: '14px',
            borderRadius: '50%',
            marginBottom: '18px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '60px',
            height: '60px',
        },
        titleStyle: {
            color: '#F8FAFC',
            fontSize: '24px',
            fontWeight: '700',
            letterSpacing: '-0.6px',
            textAlign: 'center',
            lineHeight: '1.2',
        },
        subtitleStyle: {
            color: '#94A3B8',
            fontSize: '11px',
            fontWeight: '600',
            textTransform: 'uppercase',
            letterSpacing: '2px',
            marginTop: '8px',
            textAlign: 'center',
            opacity: 0.8,
        },
        handleStyle: {
            width: '12px',
            height: '12px',
            background: 'rgba(6, 182, 212, 0.5)',
            border: '2px solid rgba(6, 182, 212, 0.8)',
            opacity: 0.6,
        },
        groupStyle: {
            backgroundColor: 'rgba(0, 0, 0, 0.4)',
            border: '1px dashed rgba(6, 182, 212, 0.3)',
            borderRadius: '24px',
            color: 'rgba(6, 182, 212, 0.7)',
            fontWeight: 'bold',
            padding: '20px',
            backdropFilter: 'blur(16px)',
            WebkitBackdropFilter: 'blur(16px)',
            boxShadow: '0 8px 32px rgba(0, 0, 0, 0.5), inset 0 0 0 1px rgba(6, 182, 212, 0.1)',
        },
    },
    linear_luxury: {
        name: 'Linear Luxury',
        emoji: '🟣',
        containerBase: {
            background: 'linear-gradient(145deg, rgba(30, 27, 75, 0.95) 0%, rgba(15, 23, 42, 0.95) 100%)',
            backdropFilter: 'blur(18px)',
            WebkitBackdropFilter: 'blur(18px)',
            border: '1px solid rgba(139, 92, 246, 0.12)',
            boxShadow: '0 20px 40px -10px rgba(124, 58, 237, 0.3), inset 0 1px 0 rgba(167, 139, 250, 0.15)',
            borderRadius: '22px',
            padding: '26px 34px',
            minWidth: '280px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
        },
        containerSelected: {
            boxShadow: '0 20px 40px -10px rgba(139, 92, 246, 0.6), 0 0 36px rgba(139, 92, 246, 0.5), inset 0 1px 0 rgba(167, 139, 250, 0.25)',
            border: '1px solid rgba(139, 92, 246, 0.7)',
            transform: 'scale(1.02)',
        },
        iconWrapper: {
            background: 'rgba(139, 92, 246, 0.1)',
            border: '1px solid rgba(139, 92, 246, 0.25)',
            boxShadow: '0 0 24px rgba(139, 92, 246, 0.2)',
            fontSize: '30px',
            padding: '14px',
            borderRadius: '50%',
            marginBottom: '18px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '60px',
            height: '60px',
        },
        titleStyle: {
            color: '#FAF5FF',
            fontSize: '23px',
            fontWeight: '700',
            letterSpacing: '-0.5px',
            textAlign: 'center',
            lineHeight: '1.2',
        },
        subtitleStyle: {
            color: '#C4B5FD',
            fontSize: '11px',
            fontWeight: '600',
            textTransform: 'uppercase',
            letterSpacing: '1.8px',
            marginTop: '8px',
            textAlign: 'center',
            opacity: 0.85,
        },
        handleStyle: {
            width: '12px',
            height: '12px',
            background: 'rgba(139, 92, 246, 0.5)',
            border: '2px solid rgba(139, 92, 246, 0.8)',
            opacity: 0.6,
        },
        groupStyle: {
            backgroundColor: 'rgba(30, 27, 75, 0.4)',
            border: '1px dashed rgba(139, 92, 246, 0.35)',
            borderRadius: '24px',
            color: 'rgba(167, 139, 250, 0.8)',
            fontWeight: 'bold',
            padding: '20px',
            backdropFilter: 'blur(16px)',
            WebkitBackdropFilter: 'blur(16px)',
            boxShadow: '0 8px 32px rgba(124, 58, 237, 0.25)',
        },
    },
    slate_premium: {
        name: 'Slate Premium',
        emoji: '🌑',
        containerBase: {
            background: 'linear-gradient(145deg, rgba(15, 23, 42, 0.95) 0%, rgba(3, 7, 18, 0.95) 100%)',
            backdropFilter: 'blur(16px)',
            WebkitBackdropFilter: 'blur(16px)',
            border: '1px solid rgba(255, 255, 255, 0.12)',
            boxShadow: '0 20px 40px -10px rgba(0, 0, 0, 0.8), inset 0 1px 0 rgba(255, 255, 255, 0.18)',
            borderRadius: '20px',
            padding: '26px 34px',
            minWidth: '280px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
        },
        containerSelected: {
            boxShadow: '0 20px 40px -10px rgba(99, 102, 241, 0.6), 0 0 32px rgba(99, 102, 241, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.22)',
            border: '1px solid rgba(99, 102, 241, 0.8)',
            transform: 'scale(1.02)',
        },
        iconWrapper: {
            background: 'rgba(255, 255, 255, 0.06)',
            border: '1px solid rgba(255, 255, 255, 0.15)',
            boxShadow: '0 0 18px rgba(255, 255, 255, 0.12)',
            fontSize: '30px',
            padding: '13px',
            borderRadius: '50%',
            marginBottom: '17px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '58px',
            height: '58px',
        },
        titleStyle: {
            color: '#F8FAFC',
            fontSize: '23px',
            fontWeight: '700',
            letterSpacing: '-0.5px',
            textAlign: 'center',
            lineHeight: '1.2',
        },
        subtitleStyle: {
            color: '#94A3B8',
            fontSize: '11px',
            fontWeight: '600',
            textTransform: 'uppercase',
            letterSpacing: '1.6px',
            marginTop: '7px',
            textAlign: 'center',
            opacity: 0.8,
        },
        handleStyle: {
            width: '11px',
            height: '11px',
            background: 'rgba(248, 250, 252, 0.6)',
            border: '2px solid rgba(148, 163, 184, 0.4)',
            opacity: 0.5,
        },
        groupStyle: {
            backgroundColor: 'rgba(15, 23, 42, 0.4)',
            border: '1px dashed rgba(148, 163, 184, 0.3)',
            borderRadius: '22px',
            color: 'rgba(248, 250, 252, 0.7)',
            fontWeight: 'bold',
            padding: '20px',
            backdropFilter: 'blur(14px)',
            WebkitBackdropFilter: 'blur(14px)',
            boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
        },
    },
    neon_dark: {
        name: 'Neon Dark',
        emoji: '⚡',
        containerBase: {
            background: 'linear-gradient(145deg, rgba(8, 8, 20, 0.95) 0%, rgba(3, 3, 10, 0.95) 100%)',
            backdropFilter: 'blur(14px)',
            WebkitBackdropFilter: 'blur(14px)',
            border: '1px solid rgba(236, 72, 153, 0.3)',
            boxShadow: '0 20px 40px -10px rgba(0, 0, 0, 0.9), 0 0 40px rgba(236, 72, 153, 0.15), inset 0 1px 0 rgba(236, 72, 153, 0.1)',
            borderRadius: '18px',
            padding: '26px 34px',
            minWidth: '280px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
        },
        containerSelected: {
            boxShadow: '0 20px 40px -10px rgba(236, 72, 153, 0.8), 0 0 50px rgba(236, 72, 153, 0.6), inset 0 0 20px rgba(236, 72, 153, 0.15)',
            border: '1px solid rgba(236, 72, 153, 0.9)',
            transform: 'scale(1.02)',
        },
        iconWrapper: {
            background: 'rgba(236, 72, 153, 0.08)',
            border: '1px solid rgba(236, 72, 153, 0.4)',
            boxShadow: '0 0 30px rgba(236, 72, 153, 0.3)',
            fontSize: '32px',
            padding: '14px',
            borderRadius: '50%',
            marginBottom: '18px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '62px',
            height: '62px',
        },
        titleStyle: {
            color: '#FCE7F3',
            fontSize: '24px',
            fontWeight: '700',
            letterSpacing: '-0.4px',
            textAlign: 'center',
            lineHeight: '1.2',
            textShadow: '0 0 20px rgba(236, 72, 153, 0.4)',
        },
        subtitleStyle: {
            color: '#F9A8D4',
            fontSize: '11px',
            fontWeight: '600',
            textTransform: 'uppercase',
            letterSpacing: '2px',
            marginTop: '8px',
            textAlign: 'center',
            opacity: 0.9,
        },
        handleStyle: {
            width: '12px',
            height: '12px',
            background: 'rgba(236, 72, 153, 0.6)',
            border: '2px solid rgba(236, 72, 153, 0.9)',
            opacity: 0.7,
            boxShadow: '0 0 10px rgba(236, 72, 153, 0.5)',
        },
        groupStyle: {
            backgroundColor: 'rgba(8, 8, 20, 0.5)',
            border: '1px dashed rgba(236, 72, 153, 0.4)',
            borderRadius: '20px',
            color: 'rgba(236, 72, 153, 0.8)',
            fontWeight: 'bold',
            padding: '20px',
            backdropFilter: 'blur(12px)',
            WebkitBackdropFilter: 'blur(12px)',
            boxShadow: '0 8px 32px rgba(0, 0, 0, 0.6), 0 0 40px rgba(236, 72, 153, 0.1)',
        },
    },
    minimal_elite: {
        name: 'Minimal Elite',
        emoji: '⚪',
        containerBase: {
            background: 'linear-gradient(145deg, rgba(255, 255, 255, 0.08) 0%, rgba(255, 255, 255, 0.04) 100%)',
            backdropFilter: 'blur(24px)',
            WebkitBackdropFilter: 'blur(24px)',
            border: '1px solid rgba(255, 255, 255, 0.18)',
            boxShadow: '0 12px 32px -8px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.25)',
            borderRadius: '24px',
            padding: '28px 36px',
            minWidth: '280px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
        },
        containerSelected: {
            boxShadow: '0 12px 32px -8px rgba(59, 130, 246, 0.5), 0 0 24px rgba(59, 130, 246, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.35)',
            border: '1px solid rgba(59, 130, 246, 0.6)',
            transform: 'scale(1.01)',
        },
        iconWrapper: {
            background: 'rgba(255, 255, 255, 0.08)',
            border: '1px solid rgba(255, 255, 255, 0.2)',
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
            fontSize: '28px',
            padding: '12px',
            borderRadius: '50%',
            marginBottom: '16px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '56px',
            height: '56px',
        },
        titleStyle: {
            color: '#FFFFFF',
            fontSize: '22px',
            fontWeight: '600',
            letterSpacing: '-0.3px',
            textAlign: 'center',
            lineHeight: '1.3',
        },
        subtitleStyle: {
            color: '#D1D5DB',
            fontSize: '10px',
            fontWeight: '500',
            textTransform: 'uppercase',
            letterSpacing: '1.4px',
            marginTop: '7px',
            textAlign: 'center',
            opacity: 0.7,
        },
        handleStyle: {
            width: '10px',
            height: '10px',
            background: 'rgba(255, 255, 255, 0.5)',
            border: '2px solid rgba(255, 255, 255, 0.3)',
            opacity: 0.4,
        },
        groupStyle: {
            backgroundColor: 'rgba(255, 255, 255, 0.04)',
            border: '1px solid rgba(255, 255, 255, 0.15)',
            borderRadius: '26px',
            color: 'rgba(255, 255, 255, 0.8)',
            fontWeight: '600',
            padding: '20px',
            backdropFilter: 'blur(20px)',
            WebkitBackdropFilter: 'blur(20px)',
            boxShadow: '0 8px 24px rgba(0, 0, 0, 0.2)',
        },
    },
    gradient_burst: {
        name: 'Gradient Burst',
        emoji: '🌈',
        containerBase: {
            background: 'linear-gradient(145deg, rgba(59, 130, 246, 0.15) 0%, rgba(139, 92, 246, 0.15) 50%, rgba(236, 72, 153, 0.15) 100%)',
            backdropFilter: 'blur(20px)',
            WebkitBackdropFilter: 'blur(20px)',
            border: '1px solid rgba(255, 255, 255, 0.15)',
            boxShadow: '0 20px 40px -10px rgba(139, 92, 246, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.2)',
            borderRadius: '22px',
            padding: '26px 34px',
            minWidth: '280px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
        },
        containerSelected: {
            boxShadow: '0 20px 40px -10px rgba(139, 92, 246, 0.7), 0 0 40px rgba(236, 72, 153, 0.5), inset 0 1px 0 rgba(255, 255, 255, 0.3)',
            border: '1px solid rgba(167, 139, 250, 0.7)',
            transform: 'scale(1.02)',
        },
        iconWrapper: {
            background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.12) 0%, rgba(236, 72, 153, 0.12) 100%)',
            border: '1px solid rgba(167, 139, 250, 0.3)',
            boxShadow: '0 0 24px rgba(139, 92, 246, 0.25)',
            fontSize: '30px',
            padding: '14px',
            borderRadius: '50%',
            marginBottom: '18px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '60px',
            height: '60px',
        },
        titleStyle: {
            color: '#FFFFFF',
            fontSize: '23px',
            fontWeight: '700',
            letterSpacing: '-0.5px',
            textAlign: 'center',
            lineHeight: '1.2',
            background: 'linear-gradient(135deg, #60A5FA 0%, #A78BFA 50%, #F472B6 100%)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            backgroundClip: 'text',
        },
        subtitleStyle: {
            color: '#DDD6FE',
            fontSize: '11px',
            fontWeight: '600',
            textTransform: 'uppercase',
            letterSpacing: '1.8px',
            marginTop: '8px',
            textAlign: 'center',
            opacity: 0.85,
        },
        handleStyle: {
            width: '12px',
            height: '12px',
            background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.6) 0%, rgba(236, 72, 153, 0.6) 100%)',
            border: '2px solid rgba(167, 139, 250, 0.8)',
            opacity: 0.7,
        },
        groupStyle: {
            backgroundColor: 'rgba(59, 130, 246, 0.08)',
            border: '1px dashed rgba(167, 139, 250, 0.4)',
            borderRadius: '24px',
            color: 'rgba(167, 139, 250, 0.9)',
            fontWeight: 'bold',
            padding: '20px',
            backdropFilter: 'blur(18px)',
            WebkitBackdropFilter: 'blur(18px)',
            boxShadow: '0 8px 32px rgba(139, 92, 246, 0.3)',
        },
    },
};

// Selection effect configurations
export const SELECTION_EFFECTS = {
    glow_scale: {
        name: 'Glow + Scale',
        emoji: '✨',
        getStyles: (theme) => theme.containerSelected,
    },
    pulse_border: {
        name: 'Pulse Border',
        emoji: '💫',
        getStyles: (theme) => ({
            ...theme.containerSelected,
            animation: 'pulse-border 2s ease-in-out infinite',
            transform: 'scale(1.01)',
        }),
    },
    subtle_lift: {
        name: 'Subtle Lift',
        emoji: '🔼',
        getStyles: (theme) => ({
            border: theme.containerSelected.border,
            boxShadow: '0 16px 32px -8px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255, 255, 255, 0.2)',
            transform: 'translateY(-4px)',
        }),
    },
};

// Helper to get theme config (with fallback)
export function getThemeConfig(themeKey = 'vercel_glass') {
    return NODE_THEMES[themeKey] || NODE_THEMES.vercel_glass;
}

// Helper to get scaled-down child node theme (for nodes inside groups)
export function getChildNodeTheme(themeKey = 'vercel_glass') {
    const theme = getThemeConfig(themeKey);
    const scale = 0.65; // Child nodes are 65% of parent size
    
    // Extract and remove minWidth from containerBase to allow flexible sizing
    const { minWidth, ...containerBaseWithoutMin } = theme.containerBase;
    
    return {
        ...theme,
        containerBase: {
            ...containerBaseWithoutMin,
            padding: '18px 22px', // Reduced from 28px 36px
            // Remove minWidth constraint - let node width prop control size
        },
        iconWrapper: {
            ...theme.iconWrapper,
            fontSize: `${parseInt(theme.iconWrapper.fontSize) * scale}px`,
            width: `${parseInt(theme.iconWrapper.width) * scale}px`,
            height: `${parseInt(theme.iconWrapper.height) * scale}px`,
            padding: `${parseInt(theme.iconWrapper.padding) * scale}px`,
            marginBottom: `${parseInt(theme.iconWrapper.marginBottom) * scale}px`,
        },
        titleStyle: {
            ...theme.titleStyle,
            fontSize: `${parseInt(theme.titleStyle.fontSize) * scale}px`,
        },
        subtitleStyle: {
            ...theme.subtitleStyle,
            fontSize: `${parseInt(theme.subtitleStyle.fontSize) * 0.9}px`,
        },
    };
}

// Helper to get group style for a theme
export function getGroupStyleForTheme(themeKey = 'vercel_glass') {
    const theme = getThemeConfig(themeKey);
    return theme.groupStyle;
}
